ci-build:
	echo 'make ci-build is successful!'

ci-lint:
	echo 'make ci-lint is successful!'

ci-test:
	echo 'make ci-test is successful!'

ci-test-system:
	echo 'make ci-test-system is successful!'

ci-release-images:
	echo 'make ci-release-images is successful!'
