include:
  - /Auto-Devops.gitlab-ci.yml

variables:
  GIT_AUTHOR_EMAIL: captivator@captive.fr
  GIT_AUTHOR_NAME: Captive Bot
  GIT_COMMITTER_EMAIL: $GIT_AUTHOR_EMAIL
  GIT_COMMITTER_NAME: $GIT_AUTHOR_NAME

  # Additional plugins
  SEMANTIC_RELEASE_PLUGINS: '@semantic-release/changelog @semantic-release/git'
  SEMANTIC_RELEASE_ARGS: ''

  # TODO: Remove this. Default values does not work we have to explicitly set them
  # @see https://gitlab.com/groups/gitlab-org/-/epics/7437
  RUBY_VERSION: 3.2.2
  NODEJS_VERSION: 20.10.0

.semantic_release_stage:
  stage: release
  image: cimg/node:lts
  dependencies: [] # Do not download artifacts
  extends:
    - .nodejs_image
  #  - .nodejs_cache
  # needs:
  #   - job: nodejs:install
  #     artifacts: true
  rules:
    - if: $CI_SCHEDULE_NAME == 'release'
      when: on_success
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
  script:
    # Set git to a branch
    - git checkout ${CI_COMMIT_REF_NAME}
    # Use local yarn cache
    - npm run release --if-present -- $SEMANTIC_RELEASE_ARGS
  allow_failure: true

nodejs:release:
  extends: .semantic_release_stage

.gitlab-test:
  needs:
    - gitlab-ci:prepare
  rules:
    - when: always

gitlab-ci:prepare:
  stage: .pre
  script:
    - cp test/Makefile Makefile
  artifacts:
    paths:
      - ./Makefile
    when: on_success

gitlab-ci:test_makefile_build:
  extends:
    - makefile:build
    - .gitlab-test

gitlab-ci:test_makefile_lint:
  extends:
    - makefile:lint
    - .gitlab-test

gitlab-ci:test_makefile_test:
  extends:
    - makefile:test
    - .gitlab-test

gitlab-ci:test_makefile_test_system:
  extends:
    - makefile:test-system
    - .gitlab-test

gitlab-ci:test_makefile_release_image:
  extends:
    - makefile:release-images
    - .gitlab-test

gitlab-ci:test_docker_dind:
  stage: test
  extends:
    - .docker_dind
    - .docker_maker_image
  variables:
    GIT_CHECKOUT_REF_NAME: 'true'
  script:
    - exit 0
