image: registry.git.captive.fr/captive/systeme/docker-maker:20.10.16-1

include:
  - remote: "https://raw.githubusercontent.com/Captive-Studio/gitlab-ci/main/Auto-Devops.gitlab-ci.yml"

before_script:
  - git checkout -B "$CI_BUILD_REF_NAME"

pre-test:check-changelog:
  stage: pre-test
  script:
    - make changelog-check
  allow_failure: true
  except:
    - tags
    - master
    - main

pre-test:check-tools:
  <<: *code_quality
  script:
    - controle-qualite.mk self-check-ruby
  allow_failure: true

pre-test:lint:rubocop:
  <<: *code_quality
  script:
    - controle-qualite.mk rubocop

pre-test:audit:bundle-audit:
  <<: *code_quality
  script:
    - controle-qualite.mk bundle-audit
  allow_failure: true

pre-test:audit:brakeman:
  <<: *code_quality
  script:
    - controle-qualite.mk brakeman
  allow_failure: true

# pre-test:lint:eslint:
#   <<: *code_quality
#   script:
#     - controle-qualite.mk eslint
#   allow_failure: true
#
# pre-test:lint:prettier:
#   <<: *code_quality
#   script:
#     - controle-qualite.mk prettier
#   allow_failure: true
#
# pre-test:lint:stylelint:
#   <<: *code_quality
#   script:
#     - controle-qualite.mk stylelint
#   allow_failure: true

build:
  <<: *docker_dind
  stage: build
  script:
    - make ci-build ci-push
  except:
    - /^backup\//
  tags:
    - docker-dind
    - heavy-job

test:most:
  <<: *docker_dind
  stage: test
  script:
    - make -e stage=test generate-env
    - make test-most
  except:
    - /^backup\//
  tags:
    - docker-dind
    - heavy-job

test:system:
  <<: *docker_dind
  stage: test
  script:
    - make -e stage=test generate-env
    - make test-system
  except:
    - /^backup\//
  tags:
    - docker-dind
    - heavy-job
  allow_failure: true
  when: manual

release:image:
  <<: *docker_dind
  stage: release
  script:
    - make ci-push-release
    - make -e REF_ID=latest ci-push-release
  only:
    - tags
    - master
    - main

review:
  variables:
    DEPLOY_STAGE: staging
  stage: review
  when: manual

deploy:staging:
  variables:
    DEPLOY_STAGE: staging
  stage: deploy
  only:
    - master
    - main

deploy:production:
  variables:
    DEPLOY_STAGE: production
  stage: deploy
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v([0-9]|[1-9][0-9]+)\.([0-9]|[1-9][0-9]+)\.([0-9]|[1-9][0-9]+)$/'
