image: registry.git.captive.fr/captive/systeme/docker-maker:20.10.16-1

include:
  - remote: 'https://raw.githubusercontent.com/Captive-Studio/gitlab-ci/main/Auto-Devops.gitlab-ci.yml'

before_script:
  - git checkout -B "$CI_BUILD_REF_NAME"


review:
  variables:
    DEPLOY_STAGE: staging
  stage: review
  when: manual

deploy:staging:
  variables:
    DEPLOY_STAGE: staging
  stage: deploy
  only:
    - master
    - main

deploy:production:
  variables:
    DEPLOY_STAGE: production
  stage: deploy
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v([0-9]|[1-9][0-9]+)\.([0-9]|[1-9][0-9]+)\.([0-9]|[1-9][0-9]+)$/'
