#!/usr/bin/env bash
set -e

BRANCH="$(git rev-parse --abbrev-ref HEAD)"
if [[ "$BRANCH" != "main" ]]; then
  echo 'Git branch should be "main"';
  exit 1;
fi

if [ ! -z "$(git status --porcelain)" ]; then
  echo 'Git repository should be clean, changes are detected';
  exit 1;
fi

# Default directories
SCRIPT_DIR="$(dirname "$0")"
cd "$SCRIPT_DIR/.."
ROOT_DIR=$(pwd)

npm install --no-save @semantic-release/exec @semantic-release/git @semantic-release/gitlab semantic-release semantic-release-gitmoji @wavevision/semantic-release --legacy-peer-deps
npx semantic-release
