# Makefile deployment based
#
# Used to have complete control over task steps
#
# Guidelines
#
# ✓ If Makefile is present, every other jobs should be disabled (NodeJS, Ruby, etc)
# ✓ Makefile script should be compatible with https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
# ✓ Simple 1:1 correspondence between gitlab job <> Makefile target
# ✓ Convention :
#     gitlab job: 'makefile:${job_name}'
#     makefile target : 'make ${job_name}'

.auto-devops:rules:only_makefile:
  rules:
    - exists:
        - Makefile

.makefile_base:
  extends:
    - .autodevops_retry
    - .docker_dind
  before_script:
    - !reference [.autodevops:script:before, script]
    - !reference [.autodevops:script:ci-registry-login, script]
    - |
      # [APK] ⏬ Install dependencies
      apk add --no-cache --quiet \
        git \
        make \
        bash

makefile:build:
  extends:
    - .makefile_base
  stage: build
  script:
    - export DOCKER_BUILD_PUSH=${DOCKER_BUILD_PUSH:-1}
    - |
      # [Docker] 📦 Build docker image used by runners ($CONTAINER_BUILDER_IMAGE) and ($CONTAINER_RUNNER_IMAGE)
    - make docker-build
  rules:
    - !reference [.auto-devops:rules:skip_builder_makefile_disabled, rules]
    - !reference [.auto-devops:rules:skip_build_disabled, rules]
    - !reference [.auto-devops:rules:only_makefile, rules]
  needs: []
  tags:
    - docker-dind
    - heavy-job

makefile:lint:
  extends:
    - .makefile_base
  stage: test
  script:
    - make lint
  rules:
    - !reference [.auto-devops:rules:skip_builder_makefile_disabled, rules]
    - !reference [.auto-devops:rules:skip_code_quality_disabled, rules]
    - !reference [.auto-devops:rules:only_makefile, rules]

makefile:test:
  extends:
    - .makefile_base
  stage: test
  script:
    - make test
  needs:
    - job: makefile:build
      artifacts: true
  tags:
    - heavy-job
  rules:
    - !reference [.auto-devops:rules:skip_builder_makefile_disabled, rules]
    - !reference [.auto-devops:rules:skip_test_disabled, rules]
    - !reference [.auto-devops:rules:only_makefile, rules]

makefile:test-system:
  extends:
    - .makefile_base
  stage: test
  script:
    - make test-system
  needs:
    - job: makefile:build
      artifacts: true
  rules:
    - !reference [.auto-devops:rules:skip_builder_makefile_disabled, rules]
    - !reference [.auto-devops:rules:skip_test_system_disabled, rules]
    - !reference [.auto-devops:rules:only_makefile, rules]
  tags:
    - heavy-job

makefile:release-images:
  extends:
    - .makefile_base
  stage: release
  script:
    - make release-images
  rules:
    - !reference [.auto-devops:rules:skip_builder_makefile_disabled, rules]
    - !reference [.auto-devops:rules:skip_non_default_branch, rules]
    - !reference [.auto-devops:rules:only_makefile, rules]
