.danger_rules:
  rules:
    - &skip_code_quality_disabled
      if: $CODE_QUALITY_ENABLED == null || $CODE_QUALITY_ENABLED == '' || $CODE_QUALITY_ENABLED == 'false'
      when: never
    - &skip_if_danger_disabled
      if: $DANGER_ENABLED == null || $DANGER_ENABLED == '' || $DANGER_ENABLED == ''
      when: never
    - &dangerjs_present_rule
      exists:
        - dangerfile.js
        - dangerfile.ts

danger-js:
  extends:
    - .nodejs_image
    - .nodejs_cache
  stage: test
  script:
    - npx danger ci
  needs:
    - job: nodejs:install
      artifacts: true
  rules:
    - <<: *skip_code_quality_disabled
    - <<: *skip_if_danger_disabled
    - <<: *dangerjs_present_rule
