.auto-devops:rules:skip_if_danger_disabled:
  rules:
    - if: $DANGER_ENABLED == null || $DANGER_ENABLED == '' || $DANGER_ENABLED == ''
      when: never

.auto-devops:rules:dangerjs_present_rule:
  rules:
    - exists:
        - dangerfile.js
        - dangerfile.ts
        - dangerfile.mts
        - dangerfile.cts

danger-js:
  extends:
    - .nodejs_image
    - .nodejs_cache
  stage: test
  script:
    - npx danger ci
  needs:
    - job: nodejs:install
      artifacts: true
  rules:
    - !reference [.auto-devops:rules:skip_code_quality_disabled, rules]
    - !reference [.auto-devops:rules:skip_if_danger_disabled, rules]
    - !reference [.auto-devops:rules:dangerjs_present_rule, rules]
