# @see https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/lib/gitlab/ci/templates/Jobs/Deploy/EC2.gitlab-ci.yml

.deploy_scalingo:
  script:
    - set -eu; echo "DEPLOY_STAGE = $DEPLOY_STAGE"
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_SSH_PRIVATE_KEY_GZ64" | base64 -d | gunzip | ssh-add -
    - make -e stage=$DEPLOY_STAGE generate-env
    - make -e stage=$DEPLOY_STAGE deploy-scalingo

scalingo:review:
  extends:
    - .auto-devops_review
    - .deploy_scalingo
  stage: review
  when: manual
  variables:
    IF_AUTO_DEVOPS_PLATFORM_TARGET: 'SCALINGO'

scalingo:staging:
  extends:
  - .auto-devops_staging
  - .deploy_scalingo
  variables:
    IF_AUTO_DEVOPS_PLATFORM_TARGET: 'SCALINGO'
    DEPLOY_STAGE: staging

scalingo:production:
  extends:
  - .auto-devops_production_auto
  - .deploy_scalingo
  variables:
    IF_AUTO_DEVOPS_PLATFORM_TARGET: 'SCALINGO'
    DEPLOY_STAGE: production

scalingo:production_manual:
  extends:
  - .auto-devops_production_manual
  - .deploy_scalingo
  variables:
    IF_AUTO_DEVOPS_PLATFORM_TARGET: 'SCALINGO'
    DEPLOY_STAGE: production
