# @see https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/lib/gitlab/ci/templates/Jobs/Deploy/EC2.gitlab-ci.yml

.deploy_scalingo:
  script:
    - set -eu; echo "CI_ENVIRONMENT_NAME = $CI_ENVIRONMENT_NAME"
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_SSH_PRIVATE_KEY_GZ64" | base64 -d | gunzip | ssh-add -
    - make -e stage=$CI_ENVIRONMENT_NAME generate-env
    - make -e stage=$CI_ENVIRONMENT_NAME deploy-scalingo

# scalingo:review:review:
#   extends:
#     - .auto-devops_review
#     - .deploy_scalingo
#   variables:
#     IF_AUTO_DEVOPS_PLATFORM_TARGET: 'SCALINGO'

scalingo:review:staging:
  extends:
    - .auto-devops_review
    - .deploy_scalingo
  environment:
    name: staging
  variables:
    IF_AUTO_DEVOPS_PLATFORM_TARGET: SCALINGO

scalingo:staging:
  extends:
    - .auto-devops_staging
    - .deploy_scalingo
  variables:
    IF_AUTO_DEVOPS_PLATFORM_TARGET: SCALINGO

scalingo:production:
  extends:
    - .auto-devops_production_auto
    - .deploy_scalingo
  variables:
    IF_AUTO_DEVOPS_PLATFORM_TARGET: SCALINGO

scalingo:production_manual:
  extends:
    - .auto-devops_production_manual
    - .deploy_scalingo
  variables:
    IF_AUTO_DEVOPS_PLATFORM_TARGET: SCALINGO
