# @see https://docs.gitlab.com/ee/ci/variables/predefined_variables.html

.deploy_makefile:
  extends:
    - .docker_dind
    - .docker_maker_image
  variables:
    GIT_STRATEGY: fetch
    GIT_CHECKOUT: 'true'
  script:
    - |
      set -eu;
      echo "CI_ENVIRONMENT_NAME = $CI_ENVIRONMENT_NAME"
      echo "CI_ENVIRONMENT_URL = $CI_ENVIRONMENT_URL"
    - make ci-deploy

makefile:review:staging:
  extends:
    - .auto-devops_review_staging
    - .deploy_makefile
  when: manual
  variables:
    IF_AUTO_DEVOPS_PLATFORM_TARGET: MAKEFILE

makefile:review:review:
  extends:
    - .auto-devops_review
    - .deploy_makefile
  when: manual
  # TODO: remove this override and support $CI_ENVIRONMENT_NAME in makefile
  environment:
    name: review
  variables:
    IF_AUTO_DEVOPS_PLATFORM_TARGET: MAKEFILE

makefile:staging:
  extends:
    - .auto-devops_staging
    - .deploy_makefile
  variables:
    IF_AUTO_DEVOPS_PLATFORM_TARGET: MAKEFILE

makefile:production:
  extends:
    - .auto-devops_production_auto
    - .deploy_makefile
  variables:
    IF_AUTO_DEVOPS_PLATFORM_TARGET: MAKEFILE

makefile:production_manual:
  extends:
    - .auto-devops_production_manual
    - .deploy_makefile
  variables:
    IF_AUTO_DEVOPS_PLATFORM_TARGET: MAKEFILE
