# @see https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/lib/gitlab/ci/templates/Jobs/Deploy/EC2.gitlab-ci.yml

variables:
  # DPL scalingo default region https://doc.scalingo.com/platform/internals/regions
  SCALINGO_REGION: osc-fr1

  # Required: the name of the app
  #
  # @type {string}
  SCALINGO_APP: $APP_NAME

  # Optional key to override only for staging environment
  #
  # @type {string}
  # @default "$SCALINGO_APP-staging"
  SCALINGO_APP_STAGING: ''

  # Optional key to override only for production environment
  #
  # @type {string}
  # @default "$SCALINGO_APP-production"
  SCALINGO_APP_PRODUCTION: ''

  # Required the api key used to deploy
  #
  # @type {string}
  SCALINGO_API_TOKEN: ''

  # Override api key only for staging environment
  #
  # @default $SCALINGO_API_TOKEN
  SCALINGO_API_TOKEN_STAGING: ''

  # Override api key only for production environment
  #
  # @default $SCALINGO_API_TOKEN
  SCALINGO_API_TOKEN_PRODUCTION: ''

.deploy_scalingo:
  # @see https://doc.scalingo.com/platform/deployment/continuous-integration/deploy-scalingo-from-gitlab
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 0
  image: ruby:3.1.3
  script:
    - gem install dpl --pre
    - SCALINGO_API_TOKEN=${SCALINGO_API_TOKEN_OVERRIDE:-$SCALINGO_API_TOKEN}
    - SCALINGO_APP=${SCALINGO_APP_OVERRIDE:-"$SCALINGO_APP-$CI_ENVIRONMENT_NAME"}
    - echo "SCALINGO_APP = $SCALINGO_APP"
    - >
      dpl
      --provider=scalingo
      --api_token=$SCALINGO_API_TOKEN
      --app=$SCALINGO_APP
      --remote="scalingo-dpl --force"
      --branch=refs/heads/master

.auto-devops_staging:
  variables:
    SCALINGO_API_TOKEN_OVERRIDE: $SCALINGO_API_TOKEN_STAGING
    SCALINGO_APP_OVERRIDE: $SCALINGO_APP_STAGING

.auto-devops_production:
  variables:
    SCALINGO_API_TOKEN_OVERRIDE: $SCALINGO_API_TOKEN_PRODUCTION
    SCALINGO_APP_OVERRIDE: $SCALINGO_APP_PRODUCTION

# scalingo:review:review:
#   extends:
#     - .auto-devops_review
#     - .deploy_scalingo
#   variables:
#     IF_AUTO_DEVOPS_PLATFORM_TARGET: SCALINGO

scalingo:review:staging:
  extends:
    - .auto-devops_review_staging
    - .deploy_scalingo
  variables:
    IF_AUTO_DEVOPS_PLATFORM_TARGET: SCALINGO

scalingo:staging:
  extends:
    - .auto-devops_staging
    - .deploy_scalingo
  variables:
    IF_AUTO_DEVOPS_PLATFORM_TARGET: SCALINGO

scalingo:production:
  extends:
    - .auto-devops_production_auto
    - .deploy_scalingo
  variables:
    IF_AUTO_DEVOPS_PLATFORM_TARGET: SCALINGO

scalingo:production_manual:
  extends:
    - .auto-devops_production_manual
    - .deploy_scalingo
  variables:
    IF_AUTO_DEVOPS_PLATFORM_TARGET: SCALINGO
