# Common mixins and anchors
#
# Guidelines
#
# ✓ All jobs should starts with `.`
# ✓ Anchor should not be used (not preserved between files)
# ✓ Including this file should not change pipeline behavior

# Only used for anchors
# ⚠️ Must be declared before use
.auto-devops_rules:
  rules:
    - &filter_platform_target
      if: '$IF_AUTO_DEVOPS_PLATFORM_TARGET && $AUTO_DEVOPS_PLATFORM_TARGET != $IF_AUTO_DEVOPS_PLATFORM_TARGET'
      when: never
    - &skip_kubernetes
      if: '$CI_KUBERNETES_ACTIVE || $KUBECONFIG'
      when: never
    - &skip_default_branch
      if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: never
    - &skip_non_default_branch
      if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: never
    - &skip_deploy_freeze
      if: $CI_DEPLOY_FREEZE && $CI_DEPLOY_FREEZE != 'false'
      when: never
    - &skip_if_review_disabled
      if: $REVIEW_ENABLED == null || $REVIEW_ENABLED == '' || $REVIEW_ENABLED == 'false'
      when: never
    - &skip_if_staging_disabled
      if: $STAGING_ENABLED == null || $STAGING_ENABLED == '' || $STAGING_ENABLED == 'false'
      when: never
    - &skip_if_staging_enabled
      if: $STAGING_ENABLED && $STAGING_ENABLED != 'false'
      when: never
    - &skip_if_canary_enabled
      if: $CANARY_ENABLED && $CANARY_ENABLED != 'false'
      when: never
    - &skip_if_incremental_rollout_enabled
      if: '$INCREMENTAL_ROLLOUT_ENABLED || $INCREMENTAL_ROLLOUT_MODE'
      when: never
    - &only_staging_enabled
      if: $STAGING_ENABLED && $STAGING_ENABLED != 'false' && ($CI_COMMIT_TAG || $CI_COMMIT_BRANCH)
    - &only_canary_enabled
      if: $CANARY_ENABLED && $CANARY_ENABLED != 'false' && ($CI_COMMIT_TAG || $CI_COMMIT_BRANCH)

.git_checkout:
  before_script:
    - &git_checkout |
      # git checkout -B "$CI_BUILD_REF_NAME" (if $GIT_CHECKOUT_REF_NAME)
      if [[ ! -z "$GIT_CHECKOUT_REF_NAME" ]];then
        git checkout -B "$CI_BUILD_REF_NAME"
      fi

# Docker in Docker mixin
#
# @example
# my_step:
#   extends
#     - .docker_dind
#   stage: ...
#
.docker_dind:
  services:
    - name: docker:20-dind
      entrypoint: [sh, -c, dockerd-entrypoint.sh $DOCKER_DAEMON_OPTIONS]
  variables:
    DOCKER_DAEMON_OPTIONS: '--registry-mirror=${CONTAINER_REGISTRY_MIRROR} --tls=false'
  tags:
    - docker-dind
  before_script:
    - unset HISTFILE
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CONTAINER_REGISTRY
    - export TEST_IMAGE=$REGISTRY_PROJECT_URL/$BUILD_SUBPATH:${BUILD_ID}-test
    - *git_checkout

# Docker make image mixin.
#
# @example
# my_step:
#   extends
#     - .docker_make_image
#   stage: ...
#
.docker_maker_image:
  image: registry.git.captive.fr/captive/systeme/docker-maker:20.10.22-0

# Use controle-qualite image and a lightweight machine
# By default use `prepare` step to fail early and fast
#
# @example
# my_step:
#   extends
#     - .code_quality
#   stage: ...
#
.code_quality:
  image: registry.git.captive.fr/captive/systeme/docker/controle-qualite:latest
  stage: prepare
  tags:
    - lightweight-job

# Enable fast compression zip
#
# @example
# my_step:
#   extends
#     - .gitlab_fast_zip
#   ...
#
.gitlab_fast_zip:
  variables:
    FF_USE_FASTZIP: 'true'
    # These can be specified per job or per pipeline
    ARTIFACT_COMPRESSION_LEVEL: fast
    CACHE_COMPRESSION_LEVEL: fast

# Mixin to trigger at staging step only when `$REVIEW_ENABLED` is truthy
#
# @example
#
# variables:
#   REVIEW_ENABLED: 'true'
#
# my_step:
#   extends
#     - .auto-devops_review
#   variables:
#     IF_AUTO_DEVOPS_PLATFORM_TARGET: 'AZURE' # Ex: will trigger only if AUTO_DEVOPS_PLATFORM_TARGET == 'AZURE'
#   script:
#     # TODO !
#
.auto-devops_review:
  stage: review
  when: manual
  variables:
    # Optional: define if needed to filter
    IF_AUTO_DEVOPS_PLATFORM_TARGET: null
  environment:
    name: review/$CI_COMMIT_REF_SLUG
  rules:
    - <<: *filter_platform_target
    - <<: *skip_kubernetes
    - <<: *skip_default_branch
    - <<: *skip_if_review_disabled
    - when: on_success

.auto-devops_stop_review:
  stage: cleanup
  variables:
    GIT_STRATEGY: none
  # script:
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    action: stop
  allow_failure: true
  rules:
    - <<: *filter_platform_target
    - <<: *skip_kubernetes
    - <<: *skip_default_branch
    - <<: *skip_if_review_disabled
    - when: manual

# Mixin to trigger review on staging environment
#
# @example
#
# variables:
#   REVIEW_ENABLED: 'true'
#
# my_step:
#   extends
#     - .auto-devops_review_staging
#   variables:
#     IF_AUTO_DEVOPS_PLATFORM_TARGET: 'AZURE' # Ex: will trigger only if AUTO_DEVOPS_PLATFORM_TARGET == 'AZURE'
#   script:
#     # TODO !
#
.auto-devops_review_staging:
  extends:
    - .auto-devops_review
    - .auto-devops_staging
  stage: review
  rules:
    - <<: *filter_platform_target
    - <<: *skip_kubernetes
    - <<: *skip_default_branch
    - <<: *skip_if_staging_disabled
    - when: manual
  allow_failure: true

# Mixin to trigger at staging step only when `$STAGING_ENABLED` is truthy
#
# @example
#
# variables:
#   STAGING_ENABLED: 'true'
#
# my_step:
#   extends
#     - .auto-devops_staging
#   variables:
#     IF_AUTO_DEVOPS_PLATFORM_TARGET: 'AZURE' # Ex: will trigger only if AUTO_DEVOPS_PLATFORM_TARGET == 'AZURE'
#   script:
#     # TODO !
#
.auto-devops_staging:
  stage: staging
  variables:
    # Optional: define if needed to filter
    IF_AUTO_DEVOPS_PLATFORM_TARGET: null
  environment:
    name: staging
    url: http://staging.$APP_NAME.$APP_DOMAIN
  rules:
    - <<: *filter_platform_target
    - <<: *skip_kubernetes
    - <<: *skip_non_default_branch
    - <<: *skip_if_staging_disabled
    - when: on_success

# Common mixin for production environment
#
# @example
# .auto-devops_production:
#   ...override any parameter
.auto-devops_production:
  stage: production
  variables:
    # Optional: define if needed to filter
    IF_AUTO_DEVOPS_PLATFORM_TARGET: null
  environment:
    name: production
    url: http://prod.$APP_NAME.$APP_DOMAIN

.auto-devops_production_auto:
  extends:
    - .auto-devops_production
  rules:
    - <<: *skip_deploy_freeze
    - <<: *filter_platform_target
    - <<: *skip_kubernetes
    - <<: *skip_non_default_branch
    - <<: *skip_if_staging_enabled
    - <<: *skip_if_canary_enabled
    - <<: *skip_if_incremental_rollout_enabled
    # Default
    - when: on_success

.auto-devops_production_manual:
  extends:
    - .auto-devops_production
  rules:
    - <<: *skip_deploy_freeze
    - <<: *filter_platform_target
    - <<: *skip_kubernetes
    - <<: *skip_non_default_branch
    - <<: *skip_if_incremental_rollout_enabled
    - <<: *only_staging_enabled
      when: manual
    - <<: *only_canary_enabled
      when: manual
# - if: '$CI_COMMIT_TAG =~ /^v([0-9]|[1-9][0-9]+)\.([0-9]|[1-9][0-9]+)\.([0-9]|[1-9][0-9]+)$/'

# Mixin to use CircleCI nodejs images
#
# @example
#
# my_step:
#   extends
#     - .nodejs_image
.nodejs_image:
  image: cimg/node:${NODEJS_VERSION}

# Mixin to use CircleCI nodejs images (+ Chrome)
#
# @example
#
# my_step:
#   extends
#     - .nodejs_image_browsers
.nodejs_image_browsers:
  image: cimg/node:${NODEJS_VERSION}-browsers

# Mixin to use CircleCI ruby images
#
# @example
#
# my_step:
#   extends
#     - .ruby_image
.ruby_image:
  image: cimg/ruby:${RUBY_VERSION}-node

# Mixin to use CircleCI ruby images (+ Chrome)
#
# @example
#
# my_step:
#   extends
#     - .ruby_image_browsers
.ruby_image_browsers:
  image: cimg/ruby:${RUBY_VERSION}-browsers
