# Common mixins and anchors
#
# Guidelines
#
# ✓ All jobs should starts with `.`
# ✓ Anchor should not be used (not preserved between files)
# ✓ Including this file should not change pipeline behavior

# Docker in Docker mixin
#
# @example
# my_step:
#   extends
#     - .docker_dind
#   stage: ...
#
.docker_dind:
  services:
    - name: docker:20.10.16-dind-alpine3.15
      command:
        [--registry-mirror, 'https://docker.mirror.captive.fr', --tls=false]
  tags:
    - docker-dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CONTAINER_REGISTRY
    - export TEST_IMAGE=$REGISTRY_PROJECT_URL/$BUILD_SUBPATH:${BUILD_ID}-test

# Use controle-qualite image and a lightweight machine
# By default use `prepare` step to fail early and fast
#
# @example
# my_step:
#   extends
#     - .code_quality
#   stage: ...
#
.code_quality:
  image: registry.git.captive.fr/captive/systeme/docker/controle-qualite:latest
  stage: prepare
  tags:
    - lightweight-job
