# Common mixins and anchors
#
# Guidelines
#
# ✓ All jobs should starts with `.`
# ✓ Anchor should not be used (not preserved between files)
# ✓ Including this file should not change pipeline behavior

# Docker in Docker mixin
#
# @example
# my_step:
#   extends
#     - .docker_dind
#   stage: ...
#
.docker_dind:
  services:
    - name: docker:20.10.16-dind-alpine3.15
      command:
        [--registry-mirror, 'https://docker.mirror.captive.fr', --tls=false]
  tags:
    - docker-dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CONTAINER_REGISTRY
    - export TEST_IMAGE=$REGISTRY_PROJECT_URL/$BUILD_SUBPATH:${BUILD_ID}-test

# Use controle-qualite image and a lightweight machine
# By default use `prepare` step to fail early and fast
#
# @example
# my_step:
#   extends
#     - .code_quality
#   stage: ...
#
.code_quality:
  image: registry.git.captive.fr/captive/systeme/docker/controle-qualite:latest
  stage: prepare
  tags:
    - lightweight-job

# Enable fast compression zip
#
# @example
# my_step:
#   extends
#     - .gitlab_fast_zip
#   ...
#
.gitlab_fast_zip:
  variables:
    FF_USE_FASTZIP: "true"
    # These can be specified per job or per pipeline
    ARTIFACT_COMPRESSION_LEVEL: "fast"
    CACHE_COMPRESSION_LEVEL: "fast"

# Mixin to trigger at staging step only when `$STAGING_ENABLED` is truthy
#
# @example
#
# variables:
#   STAGING_ENABLED: 'true'
#
# my_step:
#   extends
#     - .auto-devops_staging
#   script:
#     # TODO !
#
.auto-devops_staging:
  stage: staging
  variables:
    # Optional: define if needed to filter
    AUTO_DEVOPS_PLATFORM_FILTER: null
  rules:
    # Never if AUTO_DEVOPS_PLATFORM_FILTER is defined and AUTO_DEVOPS_PLATFORM_TARGET == AUTO_DEVOPS_PLATFORM_FILTER
    - if: '$AUTO_DEVOPS_PLATFORM_FILTER != null && $AUTO_DEVOPS_PLATFORM_FILTER != "" && $AUTO_DEVOPS_PLATFORM_TARGET != $AUTO_DEVOPS_PLATFORM_FILTER'
      when: never
    # Never if $CI_KUBERNETES_ACTIVE is defined
    - if: '$CI_KUBERNETES_ACTIVE == null || $CI_KUBERNETES_ACTIVE == ""'
      when: never
    # Never if $KUBECONFIG is defined
    - if: '$KUBECONFIG == null || $KUBECONFIG == ""'
      when: never
    # Never if on default branch (i.e. main)
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
      when: never
    # Only if $STAGING_ENABLED and on a tag or branch
    - if: '$STAGING_ENABLED && ($CI_COMMIT_TAG || $CI_COMMIT_BRANCH)'

