# Makefile deployment based
#
# Used to have complete control over task steps
#
# Guidelines
#
# ✓ If Makefile is present, every other jobs should be disabled (NodeJS, Ruby, etc)
# ✓ Makefile script should be compatible with https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
# ✓ Simple 1:1 correspondence between gitlab job <> Makefile target
# ✓ Convention :
#     gitlab job: 'makefile:${job_name}'
#     makefile target : 'make ci-${job_name}'

.makefile_docker_dind:
  extends:
    - .docker_dind
  before_script:
    - unset HISTFILE
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - export TEST_IMAGE=$REGISTRY_PROJECT_URL/$BUILD_SUBPATH:${BUILD_ID}-test
    # Inline .git_checkout > before_script
    - |
      # git checkout -B "$CI_COMMIT_REF_NAME" (if $GIT_CHECKOUT_REF_NAME)
      if [[ ! -z "$GIT_CHECKOUT_REF_NAME" ]];then
        git checkout -B "$CI_COMMIT_REF_NAME"
      fi

# TODO: use $CI_COMMIT_REF_NAME in makefile
.makefile_checkout:
  extends:
    - .git_checkout
  variables:
    GIT_STRATEGY: fetch
    GIT_CHECKOUT_REF_NAME: 'true'

.makefile_base:
  extends:
    - .autodevops_retry
    - .makefile_checkout
    - .docker_maker_image
    - .makefile_docker_dind

makefile:check-changelog:
  extends:
    - .makefile_checkout
    - .docker_maker_image
  stage: prepare
  script:
    - make ci-check-changelog
  allow_failure: true
  rules:
    - !reference [.auto-devops:rules:skip_code_quality_disabled, rules]
    - !reference [.auto-devops:rules:skip_default_branch, rules]
    - if: $CI_COMMIT_TAG
      when: never
    - !reference [.auto-devops:rules:only_makefile, rules]

makefile:lint:
  extends:
    - .makefile_base
  stage: test
  script:
    - | # make ci-lint (only if present)
      # Present
      if make -n ci-lint 2>/dev/null; then
        make ci-lint
      # Not present
      else
        echo 'Warning: `make ci-lint` not found'
      fi;
  rules:
    - !reference [.auto-devops:rules:skip_code_quality_disabled, rules]
    - !reference [.auto-devops:rules:only_makefile, rules]
  tags:
    - docker-dind
    - heavy-job

makefile:build:
  extends:
    - .makefile_base
  stage: build
  script:
    - make ci-build
  rules:
    - !reference [.auto-devops:rules:skip_build_disabled, rules]
    - !reference [.auto-devops:rules:only_makefile, rules]
  # FIXME: except:
  #   - /^backup\//
  needs: []
  tags:
    - docker-dind
    - heavy-job

makefile:test:
  extends:
    - .makefile_base
  stage: test
  script:
    - make ci-test
  # FIXME: except:
  #   - /^backup\//
  needs:
    - job: makefile:build
      artifacts: true
  tags:
    - docker-dind
    - heavy-job
  rules:
    - !reference [.auto-devops:rules:skip_test_disabled, rules]
    - !reference [.auto-devops:rules:only_makefile, rules]

makefile:test-system:
  extends:
    - .makefile_base
  stage: test
  script:
    - make ci-test-system
  # FIXME: except:
  #   - /^backup\//
  needs:
    - job: makefile:build
      artifacts: true
  rules:
    - !reference [.auto-devops:rules:skip_test_system_disabled, rules]
    - !reference [.auto-devops:rules:only_makefile, rules]
  tags:
    - docker-dind
    - heavy-job

makefile:release-images:
  extends:
    - .makefile_base
  stage: release
  script:
    - make ci-release-images
  rules:
    - !reference [.auto-devops:rules:skip_non_default_branch, rules]
    - !reference [.auto-devops:rules:only_makefile, rules]
