# Makefile deployment based
#
# Used to have complete control over task steps
#
# Guidelines
#
# ✓ If Makefile is present, every other jobs should be disabled (NodeJS, Ruby, etc)
# ✓ Makefile script should be compatible with https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
# ✓ Simple 1:1 correspondence between gitlab job <> Makefile target
# ✓ Convention :
#     gitlab job: 'makefile:${job_name}'
#     makefile target : 'make ci-${job_name}'

.makefile_present_rule:
  rules:
    - &skip_test_disabled
      if: $TEST_ENABLED == null || $TEST_ENABLED == ''
      when: never
    - &skip_test_system_disabled
      if: $TEST_SYSTEM_ENABLED == null || $TEST_SYSTEM_ENABLED == ''
      when: never
    - &makefile_present_rule
      exists:
        - Makefile

# TODO: use $CI_BUILD_REF_NAME in makefile
.makefile_checkout:
  variables:
    GIT_STRATEGY: fetch
    GIT_CHECKOUT: 'true'

makefile:check-changelog:
  extends:
    - .docker_maker_image
  stage: prepare
  script:
    - make ci-check-changelog
  allow_failure: true
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - <<: *makefile_present_rule

makefile:build:
  extends:
    - .docker_maker_image
    - .docker_dind
    - .makefile_checkout
  stage: build
  script:
    - make ci-build
  rules:
    - <<: *makefile_present_rule
  # FIXME: except:
  #   - /^backup\//
  tags:
    - docker-dind
    - heavy-job

makefile:test:
  extends:
    - .docker_maker_image
    - .docker_dind
    - .makefile_checkout
  stage: test
  script:
    - make ci-test
  # FIXME: except:
  #   - /^backup\//
  tags:
    - docker-dind
    - heavy-job
  rules:
    - <<: *skip_test_disabled
    - <<: *makefile_present_rule

makefile:test:system:
  extends:
    - .docker_maker_image
    - .docker_dind
    - .makefile_checkout
  stage: test
  script:
    - make ci-test-system
  # FIXME: except:
  #   - /^backup\//
  rules:
    - <<: *skip_test_system_disabled
    - <<: *makefile_present_rule
      when: manual
  tags:
    - docker-dind
    - heavy-job
  allow_failure: true

makefile:release:image:
  extends:
    - .docker_maker_image
    - .docker_dind
    - .makefile_checkout
  stage: release
  script:
    - make ci-release-images
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: never
    - <<: *makefile_present_rule
