

.nodejs_present_rule: &nodejs_present_rule
  exists:
    - package.json

variables:
  # Relative NPM cache path
  CI_NPM_CACHE_FOLDER: '.cache/npm'
  # Relative Cypress cache path
  CI_CYPRESS_CACHE_FOLDER: '.cache/cypress'
  # Display less npm message
  npm_config_loglevel: warn
  # NPM cache environment variable
  npm_config_cache: "$CI_PROJECT_DIR/$CI_NPM_CACHE_FOLDER"
  # Cypress cache environment variable
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/$CI_CYPRESS_CACHE_FOLDER"

nodejs:install:
  stage: prepare
  rules:
    - <<: *nodejs_present_rule
  script:
    - exit 0

nodejs:build:
  stage: build
  script:
    - npm run build --if-present
  needs:
    - job: nodejs:install
      artifacts: true
  artifacts:
    paths:
      - dist/
      - lib/
      - packages/*/lib/
      - packages/*/dist/
  rules:
    - <<: *nodejs_present_rule

nodejs:lint:
  stage: test
  needs:
    - job: nodejs:build
      artifacts: true
  tags:
    - lightweight-job
  script:
    - npm run lint --if-present
  rules:
    - <<: *nodejs_present_rule

nodejs:test:
  stage: test
  needs:
    - job: nodejs:build
      artifacts: true
  tags:
    - lightweight-job
  script:
    - npm test --if-present
  rules:
    - <<: *nodejs_present_rule

nodejs:test:e2e:
  stage: test
  needs:
    - job: nodejs:build
      artifacts: true
  tags:
    - heavy-job
  script:
    - npm run test:e2e --if-present
  rules:
    - <<: *nodejs_present_rule
