

.nodejs_present_rule: &nodejs_present_rule
  exists:
    - package.json

.nodejs_image:
  image: cypress/browsers:latest

.nodejs_cache:
  cache:
  - &nodejs_cache
    key:
      files:
        - package-lock.json
        - yarn.lock
    paths:
      - ${CI_CYPRESS_CACHE_FOLDER}
      - "**/node_modules/"
    policy: pull

variables:
  # Relative NPM cache path
  CI_NPM_CACHE_FOLDER: '.cache/npm'
  # Relative Cypress cache path
  CI_CYPRESS_CACHE_FOLDER: '.cache/cypress'
  # Display less npm message
  npm_config_loglevel: warn
  # NPM cache environment variable
  npm_config_cache: "$CI_PROJECT_DIR/$CI_NPM_CACHE_FOLDER"
  # Cypress cache environment variable
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/$CI_CYPRESS_CACHE_FOLDER"

nodejs:install:
  extends:
    - .nodejs_image
    - .gitlab_fast_zip
  stage: prepare
  rules:
    - <<: *nodejs_present_rule
  cache:
    - key: ${CI_COMMIT_REF_SLUG}
      # must be inside $CI_PROJECT_DIR for gitlab-runner caching (#3)
      paths:
        - ${CI_NPM_CACHE_FOLDER}
      when: on_success
      policy: pull-push
    - <<: *nodejs_cache
      policy: push
  script:
    - npm ci --prefer-offline --no-audit --no-optional

nodejs:build:
  extends:
    - .nodejs_image
    - .nodejs_cache
  stage: build
  script:
    - npm run build --if-present
  needs:
    - job: nodejs:install
      artifacts: true
  artifacts:
    paths:
      - dist/
      - lib/
      - packages/*/lib/
      - packages/*/dist/
  rules:
    - <<: *nodejs_present_rule

nodejs:lint:
  extends:
    - .nodejs_image
    - .nodejs_cache
  stage: test
  needs:
    - job: nodejs:build
      artifacts: true
  tags:
    - lightweight-job
  script:
    - npm run lint --if-present
  rules:
    - <<: *nodejs_present_rule

nodejs:test:
  extends:
    - .nodejs_image
    - .nodejs_cache
  stage: test
  needs:
    - job: nodejs:build
      artifacts: true
  tags:
    - lightweight-job
  script:
    - npm test --if-present
  rules:
    - <<: *nodejs_present_rule

nodejs:test:e2e:
  extends:
    - .nodejs_image
    - .nodejs_cache
  stage: test
  needs:
    - job: nodejs:build
      artifacts: true
  tags:
    - heavy-job
  script:
    - npm run test:e2e --if-present
  rules:
    - <<: *nodejs_present_rule
