# FIXME: .code_quality "except" conflicts with "rules"
# except:
#   - /^backup\//

prepare:rubocop:
  extends:
    - .code_quality
  script:
    - controle-qualite.mk rubocop
  rules:
    - exists:
        - .rubocop.yml

prepare:bundle-audit:
  extends:
    - .code_quality
  script:
    - controle-qualite.mk bundle-audit
  rules:
    - exists:
        - Gemfile
  allow_failure: true

prepare:brakeman:
  extends:
    - .code_quality
  script:
    - controle-qualite.mk brakeman
  rules:
    - exists:
        - Gemfile
  allow_failure: true
