
.ruby_present_rule: &ruby_present_rule
  exists:
    - package.json

# FIXME: .code_quality "except" conflicts with "rules"
# except:
#   - /^backup\//

prepare:check-tools:
  extends:
    - .code_quality
  script:
    - controle-qualite.mk self-check-ruby
  rules:
    - <<: *ruby_present_rule
  allow_failure: true

prepare:rubocop:
  extends:
    - .code_quality
  script:
    - controle-qualite.mk rubocop
  rules:
    - exists:
        - .rubocop.yml

prepare:bundle-audit:
  extends:
    - .code_quality
  script:
    - controle-qualite.mk bundle-audit
  rules:
    - <<: *ruby_present_rule
  allow_failure: true

prepare:brakeman:
  extends:
    - .code_quality
  script:
    - controle-qualite.mk brakeman
  rules:
    - <<: *ruby_present_rule
  allow_failure: true
