.if_default_branch: &if_default_branch
  if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

.if_non_default_branch: &if_non_default_branch
  if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH

.if_kubernetes: &if_kubernetes
  if: '$CI_KUBERNETES_ACTIVE || $KUBECONFIG'

.if_deploy_freeze: &if_deploy_freeze
  if: $CI_DEPLOY_FREEZE && $CI_DEPLOY_FREEZE != 'false'

.auto-devops:rules:skip_kubernetes:
  rules:
    - <<: *if_kubernetes
      when: never

.auto-devops:rules:skip_default_branch:
  rules:
    - <<: *if_default_branch
      when: never

.auto-devops:rules:skip_non_default_branch:
  rules:
    - <<: *if_non_default_branch
      when: never

.auto-devops:rules:skip_deploy_freeze:
  rules:
    - <<: *if_deploy_freeze
      when: never

.auto-devops:rules:skip_build_disabled:
  rules:
    - if: $BUILD_ENABLED == null || $BUILD_ENABLED == '' || $BUILD_ENABLED == 'false'
      when: never

.auto-devops:rules:skip_code_quality_disabled:
  rules:
    - if: $CODE_QUALITY_ENABLED == null || $CODE_QUALITY_ENABLED == '' || $CODE_QUALITY_ENABLED == 'false'
      when: never

.auto-devops:rules:skip_test_disabled:
  rules:
    - if: $TEST_ENABLED == null || $TEST_ENABLED == '' || $TEST_ENABLED == 'false'
      when: never

.auto-devops:rules:skip_test_system_disabled:
  rules:
    - if: $TEST_SYSTEM_ENABLED == null || $TEST_SYSTEM_ENABLED == '' || $TEST_SYSTEM_ENABLED == 'false'
      when: never

.auto-devops:rules:skip_if_review_disabled:
  rules:
    - if: $REVIEW_ENABLED == null || $REVIEW_ENABLED == '' || $REVIEW_ENABLED == 'false'
      when: never
