# Default settings
default:
  before_script:
    - !reference [.autodevops:script:before, script]

# Default script to add
#
# Usage :
# .job
#   script:
#     - !reference [.autodevops:script:before, script]
#
.autodevops:script:before:
  script:
    - !reference [.autodevops:script:shell-strict, script]
    - !reference [.autodevops:script:env-tool-versions, script]

# Configure shell to be strict
.autodevops:script:shell-strict:
  script:
    - set -euo pipefail

# Load environment variables from .tool-versions
# If a variable is already set, it is not overridden
.autodevops:script:env-tool-versions:
  script:
    - |
      # Set environment variables from .tool-versions
      if [[ -f .tool-versions ]];then
        while read line
        do
          # Convert to var name and var value
          TOOL_NAME=$(echo $line | awk '{print $1}')
          TOOL_VERSION=$(echo $line | awk '{print $2}')
          TOOL_NAME_VAR=$(echo $TOOL_NAME | tr '[:lower:]' '[:upper:]')"_VERSION"

          # Read default value
          eval "export $TOOL_NAME_VAR=\${$TOOL_NAME_VAR:-$TOOL_VERSION}"
        done < .tool-versions
      fi

# Checkout branch
#
# Force checkout branch
# FIXME: this is only used by "legacy" makefiles
# Makefile should use predefined variables
.autodevops:script:git-checkout-branch:
  script:
    - |
      # git checkout -B "$CI_COMMIT_REF_NAME" (if $GIT_CHECKOUT_REF_NAME)
      if [[ ! -z "$GIT_CHECKOUT_REF_NAME" ]];then
        git checkout -B "$CI_COMMIT_REF_NAME"
      fi

# Login local gitlab container registry
.autodevops:script:ci-registry-login:
  script:
    - unset HISTFILE
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
