# Default script to add
#
# Usage :
# .job
#   script:
#     - !reference [.autodevops:script:before, script]
#
.autodevops:script:before:
  script:
    - !reference [.autodevops:script:shell-strict, script]

# Configure shell to be strict
.autodevops:script:shell-strict:
  script:
    - set -euo pipefail

# Checkout branch
#
# Force checkout branch
# FIXME: this is only used by "legacy" makefiles
# Makefile should use predefined variables
.autodevops:script:git-checkout-branch:
  before_script:
    - |
      # git checkout -B "$CI_COMMIT_REF_NAME" (if $GIT_CHECKOUT_REF_NAME)
      if [[ ! -z "$GIT_CHECKOUT_REF_NAME" ]];then
        git checkout -B "$CI_COMMIT_REF_NAME"
      fi

# Login local gitlab container registry
.autodevops:script:ci-registry-login:
  script:
    - unset HISTFILE
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
