.auto-devops:rules:skip_if_slack_failure_disabled:
  rules:
    if: $SLACK_FAILURE_ENABLED == null || $SLACK_FAILURE_ENABLED == '' || $SLACK_FAILURE_ENABLED == 'false'
    when: never

.slack_notification:
  stage: .post
  image: curlimages/curl@sha256:d9b4541e214bcd85196d6e92e2753ac6d0ea699f0af5741f8c6cccbfcf00ef4b
  allow_failure: true

slack:failure:
  extends:
    - .slack_notification
  rules:
    - !reference [.auto-devops:rules:skip_if_slack_failure_disabled, rules]
    - !reference [.auto-devops:rules:skip_non_default_branch, rules]
    - when: on_failure
  when: on_failure
  script:
    - |
      curl -X POST --data-urlencode "payload={\"channel\": \"$SLACK_FAILURE_CHANNEL\", \"text\": \"$SLACK_FAILURE_MESSAGE\"}" $SLACK_WEBHOOK_URL
