.auto-devops:rules:skip_if_slack_failure_disabled:
  rules:
    if: $SLACK_FAILURE_ENABLED == null || $SLACK_FAILURE_ENABLED == '' || $SLACK_FAILURE_ENABLED == 'false'
    when: never

.slack_notification:
  stage: .post
  image: curlimages/curl@sha256:25d29daeb9b14b89e2fa8cc17c70e4b188bca1466086907c2d9a4b56b59d8e21
  allow_failure: true

slack:failure:
  extends:
    - .slack_notification
  rules:
    - !reference [.auto-devops:rules:skip_if_slack_failure_disabled, rules]
    - !reference [.auto-devops:rules:skip_non_default_branch, rules]
    - when: on_failure
  when: on_failure
  script:
    - |
      curl -X POST --data-urlencode "payload={\"channel\": \"$SLACK_FAILURE_CHANNEL\", \"text\": \"$SLACK_FAILURE_MESSAGE\"}" $SLACK_WEBHOOK_URL
