# @see https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Terraform/Base.gitlab-ci.yml
# @see https://docs.gitlab.com/ee/user/infrastructure/iac/terraform_template_recipes.html

# include:
# Add security scan
# - template: Jobs/SAST-IaC.gitlab-ci.yml
# rules:
#   - if: $TF_ENABLED != null && $TF_ENABLED != '' & $TF_ENABLED != 'false'

.terraform_rules:
  rules:
    - &skip_if_terraform_disabled
      if: $TF_ENABLED == null || $TF_ENABLED == '' || $TF_ENABLED == 'false'
      when: never
    - &skip_if_staging_disabled
      if: ($STAGING_ENABLED == null || $STAGING_ENABLED == '' || $STAGING_ENABLED == 'false') && $CI_ENVIRONMENT_NAME == 'staging'
      when: never

.terraform_cache:
  cache:
    key: '${TF_ROOT}'
    paths:
      - ${TF_ROOT}/.terraform/

.terraform:fmt:
  extends:
    - .terraform_image
    - .terraform_cache
  stage: validate
  script:
    - gitlab-terraform fmt
  allow_failure: true
  rules:
    - <<: *skip_if_terraform_disabled
    - when: on_success
  variables:
    TF_ROOT: ${TF_PROJECT_DIR}

.terraform:validate:
  extends:
    - .terraform_image
    - .terraform_cache
  stage: validate
  script:
    - gitlab-terraform validate
  rules:
    - <<: *skip_if_terraform_disabled
    - <<: *skip_if_staging_disabled
    - when: on_success

.terraform:build:
  extends:
    - .terraform_image
    - .terraform_cache
  stage: build
  script:
    - gitlab-terraform plan
    - gitlab-terraform plan-json
  resource_group: ${TF_STATE_NAME}
  artifacts:
    # The next line, which disables public access to pipeline artifacts, may not be available everywhere.
    # See: https://docs.gitlab.com/ee/ci/yaml/#artifactspublic
    public: false
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json
  rules:
    - <<: *skip_if_terraform_disabled
    - <<: *skip_if_staging_disabled
    - when: on_success

.terraform:deploy:
  extends:
    - .terraform_image
    - .terraform_cache
  stage: deploy
  script:
    - gitlab-terraform apply
  resource_group: ${TF_STATE_NAME}
  rules:
    - <<: *skip_if_terraform_disabled
    - <<: *skip_if_staging_disabled
    - !reference [.auto-devops:rules:skip_non_default_branch, rules]
    - if: $TF_AUTO_DEPLOY == "true"
    - when: manual

.terraform:destroy:
  extends:
    - .terraform_image
    - .terraform_cache
  stage: cleanup
  script:
    - gitlab-terraform destroy
  resource_group: ${TF_STATE_NAME}
  when: manual
  rules:
    - <<: *skip_if_terraform_disabled
    - <<: *skip_if_staging_disabled
    - when: on_success

terraform:fmt:
  extends: .terraform:fmt
  needs: []

terraform:validate:staging:
  extends: .terraform:validate
  needs: []
  variables:
    TF_STATE_NAME: staging

terraform:build:staging:
  extends:
    - .terraform:build
  environment:
    name: staging
    action: prepare
  needs:
    - job: terraform:validate:staging
      artifacts: true

terraform:deploy:staging:
  extends:
    - .terraform:deploy
  stage: staging
  dependencies:
    - terraform:build:staging
  environment:
    name: staging
    action: start
  variables:
    TF_AUTO_DEPLOY: 'true'

terraform:validate:production:
  extends: .terraform:validate
  needs: []
  variables:
    TF_STATE_NAME: production

terraform:build:production:
  extends: .terraform:build
  environment:
    name: production
    action: prepare
  needs:
    - job: terraform:validate:production
      artifacts: true

terraform:deploy:production:
  extends: .terraform:deploy
  stage: production
  dependencies:
    - terraform:build:production
  environment:
    name: production
    action: start
