# Common pipelines variables
#
# Guidelines
#
# ✓ Variables should be `UPPER_UNDERSCORE_CASE`
# ✓ Each Variables should be documented
variables:
  # Application name (for deployment, packages, etc)
  # By default $CI_PROJECT_NAME is used.
  #
  # @example
  # URL: https://git.captive.fr/captive/my-project
  # $CI_PROJECT_NAME // 'my-project'
  #
  # @type {string}
  APP_NAME: $CI_PROJECT_NAME

  # Default domain for deployment `env.app.$APP_DOMAIN`
  #
  # @type {string}
  APP_DOMAIN: captive.dev

  # Enable Review step
  #
  # @type {'true'|''}
  REVIEW_ENABLED: 'true'

  # Deploy to staging step
  #
  # @type {'true'|''}
  STAGING_ENABLED: 'true'

  # Deploy canary release
  #
  # @type {'true'|''}
  CANARY_ENABLED: ''

  # Incremental rollout release (10%, 20%, etc)
  #
  # @type {'true'|''}
  INCREMENTAL_ROLLOUT_ENABLED: ''

  # Deployment Platform Target
  #
  # @type {''| 'HEROKU' | 'SCALINGO' | 'SCALEWAY' | 'MAKEFILE'}
  AUTO_DEVOPS_PLATFORM_TARGET: ''

  # Docker image registry URL, where image are pushed
  #
  # @type {string}
  CONTAINER_REGISTRY: registry.git.captive.fr

  # Required variables for docker.mk
  #
  # @type {string}
  REGISTRY_PROJECT_URL: $CONTAINER_REGISTRY/$CI_PROJECT_PATH

  BUILD_SUBPATH: dev
  BUILD_ID: $CI_COMMIT_SHORT_SHA
  REF_ID: $CI_COMMIT_REF_SLUG

  #
  # docker-dind
  #

  # @internal Use driver overlay2 for performances
  DOCKER_DRIVER: overlay2

  # @internal Disable TLS
  DOCKER_TLS_CERTDIR: ''

  # @internal
  DEPLOY_SSH_KNOWN_HOSTS_BASE64: ''

  #
  # Postgres
  #
  POSTGRES_DB: ci_test
  POSTGRES_USER: ci_db_user
  POSTGRES_PASSWORD: ci_db_password
  DATABASE_URL: 'postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB'

  #
  # Redis
  #
  REDIS_URL: redis://redis:6379

  #
  # NodeJS
  #

  # NodeJS version used (with `image: cimg/node-${NODEJS_VERSION}`)
  #
  # @see https://circleci.com/developer/images/image/cimg/node
  NODEJS_VERSION: 19.5.0

  #
  # Ruby
  #

  # NodeJS version used (with `image: cimg/ruby-${NODEJS_VERSION}`)
  #
  # @see https://circleci.com/developer/images/image/cimg/ruby
  RUBY_VERSION: 3.2.0
