# Common pipelines variables
#
# Guidelines
#
# ✓ Variables should be `UPPER_UNDERSCORE_CASE`
# ✓ Each Variables should be documented
variables:
  # Enable Review step
  REVIEW_ENABLED: 'true'
  # Deploy to staging step
  STAGING_ENABLED: 'true'
  # Deploy canary release
  CANARY_ENABLED: ''
  # Incremental rollout release (10%, 20%, etc)
  INCREMENTAL_ROLLOUT_ENABLED: ''

  # Deployment Platform Target : "SCALINGO" | "SCALEWAY" | "MAKEFILE"
  AUTO_DEVOPS_PLATFORM_TARGET: ''

  # Docker image registry, where image are pushed
  CONTAINER_REGISTRY: registry.git.captive.fr

  # Required variables for docker.mk
  REGISTRY_PROJECT_URL: $CONTAINER_REGISTRY/$CI_PROJECT_PATH
  BUILD_SUBPATH: dev
  BUILD_ID: $CI_COMMIT_SHORT_SHA
  REF_ID: $CI_COMMIT_REF_SLUG

  #
  # docker-dind
  #

  # Use driver overlay2 for performances
  DOCKER_DRIVER: overlay2
  # Disable TLS
  DOCKER_TLS_CERTDIR: ''

  DEPLOY_SSH_KNOWN_HOSTS_BASE64: ''

  #
  # Postgres
  #
  POSTGRES_DB: ci_test
  POSTGRES_USER: ci_db_user
  POSTGRES_PASSWORD: ci_db_password
  DATABASE_URL: 'postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB'

  #
  # Redis
  #
  REDIS_URL: redis://redis:6379
