
# Merge Request workflow
# @see https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/lib/gitlab/ci/templates/Workflows/MergeRequest-Pipelines.gitlab-ci.yml
workflow:
  rules:
    # If merge request pipeline
    - if: $CI_MERGE_REQUEST_IID
    # If a tag commit
    - if: $CI_COMMIT_TAG
    # If a default branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    # If a well known development branch
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_COMMIT_BRANCH == 'develop'
